language: go

go:
  - 1.2.2

install:
  - make all

script:
  - make test

notifications:
  email:
    recipients:
      - chaitanya@3bandar.org
      - pradeep.chhetri89@gmail.com
    on_success: change
    on_failure: always
